version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "master-java8"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
