package org.waveywaves.jenkins.plugins.tekton.generator;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests to verify that generated POJOs properly extend BaseStep
 * and have correct Jenkins annotations for plugin integration.
 */
public class JenkinsIntegrationTest {

    @TempDir
    Path tempDir;

    private Path outputDir;
    private Path crdDir;
    private EnhancedCrdProcessor processor;

    @BeforeEach
    void setUp() throws IOException {
        outputDir = tempDir.resolve("generated-sources");
        crdDir = tempDir.resolve("crds");
        processor = new EnhancedCrdProcessor();
        
        Files.createDirectories(outputDir);
        Files.createDirectories(crdDir);
        
        // Copy mock CRD files
        copyMockCrdsToTempDir();
    }
    
    private void copyMockCrdsToTempDir() throws IOException {
        String[] mockFiles = {
            "mock-simple-task.yaml",
            "mock-complex-pipeline.yaml", 
            "mock-edge-case-crd.yaml"
        };
        
        for (String fileName : mockFiles) {
            Path sourceFile = Paths.get("src/test/resources/org/waveywaves/jenkins/plugins/tekton/generator", fileName);
            Path targetFile = crdDir.resolve(fileName);
            if (Files.exists(sourceFile)) {
                Files.copy(sourceFile, targetFile);
            }
        }
    }

    @Test
    void testBaseStepInheritance() throws Exception {
        // Given - Use files generated by Maven plugin instead of generating new ones
        Path generatedDir = Paths.get("target/generated-sources/tekton");
        
        // Then - Check if files exist and have correct structure
        Path stepClass = generatedDir.resolve("org/waveywaves/jenkins/plugins/tekton/generated/tasks/v1/CreateTaskTyped.java");
        if (Files.exists(stepClass)) {
            String classContent = Files.readString(stepClass);

            // Verify inheritance
            assertTrue(classContent.contains("extends BaseStep"), "Should extend BaseStep");
            
            // Verify import statement
            assertTrue(classContent.contains("import org.waveywaves.jenkins.plugins.tekton.client.build.BaseStep;"), 
                "Should import BaseStep");
            
            // Verify class declaration is correct
            Pattern classPattern = Pattern.compile("public class CreateTaskTyped\\s+extends BaseStep");
            Matcher matcher = classPattern.matcher(classContent);
            assertTrue(matcher.find(), "Class declaration should be syntactically correct");
        } else {
            // Skip test if files not generated yet
            System.out.println("Generated files not found, skipping test. Run 'mvn compile' first.");
        }
    }

    @Test
    void testDataBoundConstructorAnnotation() throws Exception {
        // Given - Use files generated by Maven plugin
        Path generatedDir = Paths.get("target/generated-sources/tekton");
        
        // Then - Check if files exist and have correct structure
        Path stepClass = generatedDir.resolve("org/waveywaves/jenkins/plugins/tekton/generated/tasks/v1/CreateTaskTyped.java");
        if (Files.exists(stepClass)) {
            String classContent = Files.readString(stepClass);

            // Verify @DataBoundConstructor annotation
            assertTrue(classContent.contains("@DataBoundConstructor"), "Should have @DataBoundConstructor annotation");
            
            // Verify import for annotation
            assertTrue(classContent.contains("import org.kohsuke.stapler.DataBoundConstructor;"), 
                "Should import DataBoundConstructor");
            
            // Verify constructor structure
            Pattern constructorPattern = Pattern.compile("@DataBoundConstructor\\s+public CreateTaskTyped\\s*\\(");
            Matcher matcher = constructorPattern.matcher(classContent);
            assertTrue(matcher.find(), "Constructor should be properly annotated");
            
            // Verify constructor calls super()
            assertTrue(classContent.contains("super();"), "Constructor should call super()");
        } else {
            // Skip test if files not generated yet
            System.out.println("Generated files not found, skipping test. Run 'mvn compile' first.");
        }
    }

    @Test
    void testJenkinsStepStructure() throws Exception {
        // Given - Use files generated by Maven plugin
        Path generatedDir = Paths.get("target/generated-sources/tekton");
        
        // Then - Check if files exist and have correct structure
        Path v1StepClass = generatedDir.resolve("org/waveywaves/jenkins/plugins/tekton/generated/pipelines/v1/CreatePipelineTyped.java");
        if (Files.exists(v1StepClass)) {
            String classContent = Files.readString(v1StepClass);

            // Verify complete Jenkins Step structure
            assertTrue(classContent.contains("public class CreatePipelineTyped") && classContent.contains("extends BaseStep"), 
                "Should have correct class declaration with inheritance");
            
            // Verify required imports for Jenkins integration
            assertTrue(classContent.contains("import org.waveywaves.jenkins.plugins.tekton.client.build.BaseStep;"), 
                "Should import BaseStep");
            assertTrue(classContent.contains("import org.kohsuke.stapler.DataBoundConstructor;"), 
                "Should import DataBoundConstructor");
            
            // Verify constructor is properly structured
            assertTrue(classContent.contains("@DataBoundConstructor"), "Should have constructor annotation");
            assertTrue(classContent.contains("public CreatePipelineTyped("), "Should have public constructor");
            assertTrue(classContent.contains("super();"), "Should call super constructor");
        } else {
            // Skip test if files not generated yet
            System.out.println("Generated files not found, skipping test. Run 'mvn compile' first.");
        }
    }

    @Test
    void testMultiVersionJenkinsIntegration() throws Exception {
        // Given - Use files generated by Maven plugin
        Path generatedDir = Paths.get("target/generated-sources/tekton");
        
        // Then - Check if files exist and have correct structure
        // Test both v1 and v1beta1 versions
        String[] versions = {"v1", "v1beta1"};
        
        for (String version : versions) {
            Path stepClass = generatedDir.resolve(String.format(
                "org/waveywaves/jenkins/plugins/tekton/generated/pipelines/%s/CreatePipelineTyped.java", 
                version));
            
            if (Files.exists(stepClass)) {
                String classContent = Files.readString(stepClass);
                
                // Verify each version has proper Jenkins integration
                assertTrue(classContent.contains("extends BaseStep"), 
                    version + " should extend BaseStep");
                assertTrue(classContent.contains("@DataBoundConstructor"), 
                    version + " should have DataBoundConstructor");
                assertTrue(classContent.contains("super();"), 
                    version + " should call super()");
                
                // Verify package is version-specific
                assertTrue(classContent.contains("package org.waveywaves.jenkins.plugins.tekton.generated.pipelines." + version + ";"), 
                    version + " should have correct package declaration");
            } else {
                // Skip test if files not generated yet
                System.out.println("Generated files not found for version " + version + ", skipping test. Run 'mvn compile' first.");
            }
        }
    }

    @Test
    void testEdgeCaseJenkinsIntegration() throws Exception {
        // Given - Use files generated by Maven plugin
        Path generatedDir = Paths.get("target/generated-sources/tekton");
        
        // Then - Check if files exist and have correct structure
        Path stepClass = generatedDir.resolve("org/waveywaves/jenkins/plugins/tekton/generated/tasks/v1/CreateTaskTyped.java");
        if (Files.exists(stepClass)) {
            String classContent = Files.readString(stepClass);

            // Verify Jenkins integration is preserved even with edge cases
            assertTrue(classContent.contains("extends BaseStep"), 
                "Edge case class should still extend BaseStep");
            assertTrue(classContent.contains("@DataBoundConstructor"), 
                "Edge case class should have required annotations");
            
            // Verify it compiles to valid Java (basic syntax check)
            assertFalse(classContent.contains("class class"), "Should not have syntax errors");
            assertFalse(classContent.contains("import import"), "Should not have duplicate imports");
            
            // Verify class structure is correct despite edge cases
            Pattern classPattern = Pattern.compile("public class CreateTaskTyped\\s+extends BaseStep\\s*\\{");
            Matcher matcher = classPattern.matcher(classContent);
            assertTrue(matcher.find(), "Class structure should be valid despite edge cases");
        } else {
            // Skip test if files not generated yet
            System.out.println("Generated files not found, skipping test. Run 'mvn compile' first.");
        }
    }

    @Test
    void testPackageAndClassNaming() throws Exception {
        // Given - Use files generated by Maven plugin
        Path generatedDir = Paths.get("target/generated-sources/tekton");
        
        // Then - Check if files exist and have correct structure
        Path stepClass = generatedDir.resolve("org/waveywaves/jenkins/plugins/tekton/generated/tasks/v1/CreateTaskTyped.java");
        if (Files.exists(stepClass)) {
            String classContent = Files.readString(stepClass);

            // Verify naming conventions follow Jenkins standards
            assertTrue(classContent.contains("package org.waveywaves.jenkins.plugins.tekton.generated.tasks.v1;"), 
                "Package name should follow convention");
            assertTrue(classContent.contains("public class CreateTaskTyped"), 
                "Class name should follow Create*Typed pattern");
            
            // Verify it doesn't conflict with existing Jenkins classes
            assertFalse(classContent.contains("class Task "), "Should not conflict with existing Task classes");
            assertFalse(classContent.contains("class Pipeline "), "Should not conflict with existing Pipeline classes");

            // testing top level classes
        } else {
            // Skip test if files not generated yet
            System.out.println("Generated files not found, skipping test. Run 'mvn compile' first.");
        }
    }

    @Test 
    void testGeneratedCodeSyntaxValidity() throws Exception {
        // Given - Use files generated by Maven plugin
        Path generatedDir = Paths.get("target/generated-sources/tekton");
        
        // Then - Check if files exist and have correct structure
        Path stepClass = generatedDir.resolve("org/waveywaves/jenkins/plugins/tekton/generated/pipelines/v1/CreatePipelineTyped.java");
        if (Files.exists(stepClass)) {
            String classContent = Files.readString(stepClass);
            
            // Debug: Print first few characters
            System.out.println("File content starts with: '" + classContent.substring(0, Math.min(50, classContent.length())) + "'");

            // Basic syntax validation - handle potential BOM or special characters
            assertTrue(classContent.trim().startsWith("package "), "Should start with package declaration");
            assertTrue(classContent.contains("public class "), "Should have public class declaration");
            
            // Verify proper brace matching (basic check)
            long openBraces = classContent.chars().filter(ch -> ch == '{').count();
            long closeBraces = classContent.chars().filter(ch -> ch == '}').count();
            assertEquals(openBraces, closeBraces, "Braces should be balanced");
            
            // Verify no common syntax errors
            assertFalse(classContent.contains(";;"), "Should not have double semicolons");
            assertFalse(classContent.contains("{{"), "Should not have double open braces");
            assertFalse(classContent.contains("}}"), "Should not have double close braces");
            assertFalse(classContent.contains("class class"), "Should not have duplicate class keyword");
        }
    }

    @Test
    void testDirectoryProcessingWithoutInheritance() throws Exception {
        // Given
        processor.processDirectory(crdDir, outputDir, 
            "org.waveywaves.jenkins.plugins.tekton.generated", false);

        // Then - Should still generate classes but without BaseStep inheritance
        Path packageDir = outputDir.resolve("org/waveywaves/jenkins/plugins/tekton/generated");
        if (Files.exists(packageDir)) {
            // Just verify that some files are generated
            boolean hasGeneratedFiles = Files.walk(packageDir)
                .anyMatch(path -> path.toString().endsWith(".java"));
            assertTrue(hasGeneratedFiles || !Files.exists(packageDir), 
                "Should generate files or handle gracefully");
        }
    }
}