name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  TEKTON_VERSION: v0.56.0
  KIND_VERSION: v0.20.0
  KUBECTL_VERSION: v1.28.0
  JAVA_VERSION: 21
  KIND_CLUSTER_NAME: tekton-e2e-test   

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    # --- Checkout ------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # --- Java ----------------------------------------------------------
    - name: Setup Temurin ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: maven

    # --- Caches --------------------------------------------------------
    - name: Cache Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    # --- Tooling (Kind + kubectl) -------------------------------------
    - name: Install Kind & kubectl
      run: |
        curl -Lo kind https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64
        chmod +x kind && sudo mv kind /usr/local/bin/
        curl -Lo kubectl https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
        chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        kind version && kubectl version --client

    # --- Create Kind cluster early (faster) ---------------------------
    - name: Create Kind cluster
      run: |
        kind create cluster --name "${KIND_CLUSTER_NAME}" --wait 120s
        kubectl cluster-info --context "kind-${KIND_CLUSTER_NAME}"

    # --- Build plugin HPI (skip tests) --------------------------------
    - name: mvn package (skip tests) – build HPI
      run: |
        mvn -ntp -B clean package -DskipTests

    # --- Run E2E tests -------------------------------------------------
    - name: Run E2E tests
      env:
        SKIP_CLEANUP: ${{ runner.debug == '1' && 'true' || 'false' }}
      run: |
        echo "SKIP_CLEANUP=${SKIP_CLEANUP}"
        mvn -ntp -B test \
          -P !quick -Dtest="*E2ETest*" \
          -Dmaven.test.failure.ignore=false \
          -Djava.awt.headless=true \
          -Xmx2g

    - name: Dump Kind & Maven logs (on failure)
      if: failure()
      run: |
        echo "::group::Kind‑cluster state"
        kind get clusters
        kubectl get all -A || true
        echo "::endgroup::"
        echo "::group::Recent events"
        kubectl get events -A --sort-by=.lastTimestamp | tail -30 || true
        echo "::endgroup::"
        echo "::group::Surefire summary"
        find target/surefire-reports -name '*.txt' -type f -exec cat {} \; || true
        echo "::endgroup::"

    # --- Upload reports & logs ----------------------------------------
    - name: Upload test artefacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-artifacts
        path: |
          target/surefire-reports/**
          target/*.log
          target/site/jacoco/**
        retention-days: 14

    # --- Cleanup -------------------------------------------------------
    - name: Cleanup Kind
      if: always() && env.SKIP_CLEANUP != 'true'
      run: |
        kind delete cluster --name "${KIND_CLUSTER_NAME}" || true

# ------------------------------ Unit -----------------------------------
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: maven
    - name: Run unit tests
      run: |
        mvn -ntp -B clean test -Dtest="!*E2ETest*"
    - name: Upload unit test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-reports
        path: target/surefire-reports/**
        retention-days: 14

  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    needs: unit-tests
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: maven
    - name: mvn package
      run: mvn -ntp -B clean package -DskipTests
    - name: Upload plugin .hpi
      uses: actions/upload-artifact@v4
      with:
        name: tekton-plugin-hpi
        path: target/*.hpi
        retention-days: 30
